// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/go-nunu/nunu-layout-advanced/internal/job"
	"github.com/go-nunu/nunu-layout-advanced/pkg/log"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewApp(viperViper *viper.Viper, logger *log.Logger) (*job.Job, func(), error) {
	jobJob := job.NewJob(logger)
	return jobJob, func() {
	}, nil
}

// wire.go:

var JobSet = wire.NewSet(job.NewJob)
