// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/go-nunu/nunu-layout/internal/job"
	"github.com/go-nunu/nunu-layout/pkg/db"
	"github.com/go-nunu/nunu-layout/pkg/log"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

// wire.go 初始化模块
func NewApp(viperViper *viper.Viper, logger *log.Logger) (*job.Job, func(), error) {
	gormDB := db.NewDB(viperViper)
	jobJob := job.NewJob(gormDB, logger)
	return jobJob, func() {
	}, nil
}
